# Generated by Django 2.2.14 on 2021-04-28 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletter_category'),
        ('users', '0002_auto_20210427_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Newsletter',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='newsletters.Newsletter'),
            preserve_default=False,
        ),
    ]
