# Generated by Django 2.2.14 on 2021-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ManyToManyField(related_name='Newsletters', to='tags.Tag'),
        ),
    ]
